name: Hello Word!
on: 
  push:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello Word!"
      - name: print date
        run: |
          date
      - name: print ls
        run: |
          ls -l